### PR TITLE
Feat#82: Google Authentication, Login and Signup backend

### PR DESCRIPTION
**Pull request by SaurabhS55**
Hey @mohitparmar1, I have added new feature called **login with google**. While working on this feature, I have noticed that login and signup backend is not developed yet. To work on google auth, it was neccessary to develop  basic login and signup backend.
so, firstly I developed it and then I implemented this feature.
Features:
1. Login and Signup backend.
2. "Login with google" : Used  react-oauth/google npm library for google auth.
3. React toasify toasts: used for better and user friendly UI.

### CODE REVIEW

**Comment by SaurabhS55** [comment]
@mohitparmar1, review it once.

**Review by anasadh — APPROVED** [review]
It looks fine.

**Comment by mohitparmar1** [comment]
please resolve conflicts to merge the pr!

**Comment by SaurabhS55** [comment]
> please resolve conflicts to merge the pr!

Should I?

**Comment by SaurabhS55** [comment]
> please resolve conflicts to merge the pr!

@mohitparmar1 plzz preview the version once, before merging the pr.

**Comment by SaurabhS55** [comment]
Hey @mohitparmar1 any update on review ?

**Pull request merged**
