### PR TITLE
Make description box functionable and responsive #100

### PR DESCRIPTION
**Pull request by HimankPatidar**
#100  Fixed : Here I make Description and Reviews Functionable you can post the comment upload the image and give rating. And i also make them responsive together with ProductDiplay page. 

https://github.com/mohitparmar1/Shopy/assets/87924614/81b679bb-479f-4112-a35b-7fd9e07bb7ce

### CODE REVIEW

**Comment by mohitparmar1** [comment]
@HimankPatidar, I think you forgot to pull the changes, and that removed a few of our previous code. If I merge this PR now, it will no longer be available. Could you raise the issue and just mention me about this PR?

**Comment by mohitparmar1** [comment]
please raise different pr!

**Comment by HimankPatidar** [comment]
@mohitparmar1  do i need to make pr for both of them or only #63

**Comment by mohitparmar1** [comment]
make different, so that your both issue will be individual pr!

**Comment by HimankPatidar** [comment]
ok

**Pull request closed without merging**
