### PR TITLE
Add contact page

### PR DESCRIPTION
**Pull request by Mandakini-S**
Under issue #73 
I have added contact page. 
Screenshot:
Screenshot from 2024-05-14 23-38-28

### CODE REVIEW

**Comment by mohitparmar1** [comment]
please resolve conflicts to merge pr!

**Comment by Mandakini-S** [comment]
@mohitparmar1 Conflict has been resolved!

**Comment by mohitparmar1** [comment]
> @mohitparmar1 Conflict has been resolved!
resolve conflicts

**Comment by Mandakini-S** [comment]
@mohitparmar1 I have resolve the conflict , you can now close issue #73.

**Pull request merged**
