### PR TITLE
Fix the Carousal  #33

### PR DESCRIPTION
**Pull request by HimankPatidar**
#33  Carousal page on home page is created with Tailwind CSS marked this under GSSOC24 this is my first contribution on open source

https://github.com/mohitparmar1/Shopy/assets/87924614/37cd73be-3432-42a2-acf4-58afdecd7007

### CODE REVIEW

**Comment by HimankPatidar** [comment]
hey , I got this conflict (This branch has conflicts that must be resolved) while creating a pull request my pull request is created but i got this conflict . can you tell me what this issue is and how to resolve this
Screenshot 2024-05-11 140302

**Comment by mohitparmar1** [comment]
hey! thanks for the pr, are you still facing any issues? also if possible can you add a few images that automatically change?

**Comment by HimankPatidar** [comment]
issue is solved i will add images

**Comment by mohitparmar1** [comment]
few conflicts to be resolved

**Comment by HimankPatidar** [comment]
Hey Bro, Can you tell me where is the problem that it says deployement is failed. By the way i added images in Carousel and it works perfectly 

https://github.com/mohitparmar1/Shopy/assets/87924614/42a151a9-b30f-4f3f-9ebd-f54e5a44c12d

**Pull request closed without merging**
